@echo off
cd /d "%cd%"
echo cleaning %cd%...

REM Visual Studio...
echo cleaning packages...
FOR /d /r . %%d IN (packages\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning pkg...
FOR /d /r . %%d IN (pkg\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning pkgobj...
FOR /d /r . %%d IN (pkgobj\) DO @IF EXIST "%%d" rd /s /q "%%d"

REM _ReSharper
echo cleaning _ReSharper...
FOR /d /r . %%d IN (_ReSharper.*) DO @IF EXIST "%%d\" rd /s /q "%%d"

REM VSCode...
echo cleaning .vscode...
FOR /d /r . %%d IN (.vscode\) DO @IF EXIST "%%d" rd /s /q "%%d"

REM angular...
echo cleaning node_modules...
FOR /d /r . %%d IN (node_modules\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning e2e...
IF EXIST e2e\ (
	del /F /Q e2e\*.js 2>NUL
	del /F /Q e2e\*.map 2>NUL
)

REM IntelliJ/Android Studio...
echo cleaning captures...
IF EXIST captures\ rd /s /q captures
echo cleaning build...
FOR /d /r . %%d IN (build\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning .idea...
FOR /d /r . %%d IN (.idea\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning .c9...
FOR /d /r . %%d IN (.c9\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning gradle...
FOR /d /r . %%d IN (.gradle\) DO @IF EXIST "%%d" rd /s /q "%%d"

REM Other
echo cleaning dist...
FOR /d /r . %%d IN (dist\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning dist-server...
FOR /d /r . %%d IN (dist-server\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning tmp...
FOR /d /r . %%d IN (tmp\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning bin...
FOR /d /r . %%d IN (bin\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning obj...
FOR /d /r . %%d IN (obj\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning out-tsc...
FOR /d /r . %%d IN (out-tsc\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning .sass-cache...
FOR /d /r . %%d IN (.sass-cache\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning coverage...
FOR /d /r . %%d IN (coverage\) DO @IF EXIST "%%d" rd /s /q "%%d"
echo cleaning typings...
FOR /d /r . %%d IN (typings\) DO @IF EXIST "%%d" rd /s /q "%%d"

echo cleaning other files...
del /F /Q /S *.msu 2>NUL
del /F /Q /S *.msi 2>NUL
del /F /Q /S *.apk 2>NUL
del /F /Q /S *.tmp 2>NUL
del /F /Q /S *.sublime-workspace 2>NUL
del /F /Q /S *.locked 2>NUL
del /F /Q /S *.lock 2>NUL
del /F /Q /S *.lck 2>NUL
del /F /Q /S *.log 2>NUL
del /F /Q /S *.iml 2>NUL
del /F /Q /S *.launch 2>NUL
del /F /Q /S UpgradeLog.ht* 2>NUL
del /F /Q /S .DS_Store 2>NUL
del /F /Q /S Thumbs.db 2>NUL
del /F /Q /S local.properties 2>NUL
del /F /Q /S .externalNativeBuild 2>NUL
del /F /Q /S .project 2>NUL
del /F /Q /S .classpath 2>NUL

echo done
